### PR TITLE
Adds CSS coding to webpages and  re-adding of images and docs links i…

### PR DESCRIPTION
**Pull request by Srhymes1010**
GitHub could not transfer my documents and image folders from the other branch. So, I had to redo both of them.

### CODE REVIEW

**Comment by Srhymes1010** [comment]
Hi, I am not sure why it is saying that there is a branch conflict, and I'm not sure how to resolve the conflicts. Would you please take a look and see what is going on. So I can fix what is going on.
Thanks, I appreciate it.

**Comment by axamei** [comment]
Hi @Srhymes1010 I will take a look at this later today and let you know if we need to meet.

**Comment by Srhymes1010** [comment]
I appreciate your help.

**Comment by axamei** [comment]
@Srhymes1010 it looks like the branch did not include the latest version of the main branch that included the HTML assignment. Pull/fetch this branch and let me know if all the work you did is there.

**Comment by Srhymes1010** [comment]
Ok, I did pull/fetch on the branch, and I think all of my work is there.

**Comment by axamei** [comment]
@Srhymes1010 i undid the revert you did so your CSS work is restored. i made some changes to your HTML and CSS. there were issues with color contrast so I changed the colors so that it could be easier to see. please feel free to change, but please make sure that it meets a color contrast ratio of at least 4.5:1. there are several tools out there to help you with this. you can use chrome devtools.

**Pull request merged**
